// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NepseApp.Models;

namespace NepseApp.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NepseApp.DataModels.LiveDataModel", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<double>("Close")
                        .HasColumnType("REAL")
                        .HasColumnName("close");

                    b.Property<double>("High")
                        .HasColumnType("REAL")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("REAL")
                        .HasColumnName("low");

                    b.Property<double>("Ltp")
                        .HasColumnType("REAL")
                        .HasColumnName("ltp");

                    b.Property<double>("Ltv")
                        .HasColumnType("REAL")
                        .HasColumnName("ltv");

                    b.Property<double>("Open")
                        .HasColumnType("REAL")
                        .HasColumnName("open");

                    b.Property<double>("PercentChange")
                        .HasColumnType("REAL")
                        .HasColumnName("percent_change");

                    b.Property<double>("PointChange")
                        .HasColumnType("REAL")
                        .HasColumnName("point_change");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL")
                        .HasColumnName("volume");

                    b.HasKey("Symbol")
                        .HasName("pk_live");

                    b.ToTable("live");
                });
#pragma warning restore 612, 618
        }
    }
}
